# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slatewave < Formula
  desc "One palette across every tool you live in — install the Slatewave family from one CLI."
  homepage "https://getslatewave.com"
  version "0.0.3"
  license "WTFPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.3/slatewave-cli_0.0.3_darwin_amd64.tar.gz"
      sha256 "03ff05dd7a6d0e57a9248296563fed164a136c46966bf1ef334bfd3b0445ebac"

      define_method(:install) do
        bin.install "slatewave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.3/slatewave-cli_0.0.3_darwin_arm64.tar.gz"
      sha256 "067baf036b1732cd3f96b0f2740b0a5fd9f439d62a1b0209df3a34d64ff7ce6f"

      define_method(:install) do
        bin.install "slatewave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.3/slatewave-cli_0.0.3_linux_amd64.tar.gz"
      sha256 "791125c389ec244f39d472ee2cb001b308dfafe7227b557f8845885181dd6eec"
      define_method(:install) do
        bin.install "slatewave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.3/slatewave-cli_0.0.3_linux_arm64.tar.gz"
      sha256 "c77e58daf82bb368398649bee70a593686177bb24ec5d2b3c12e225dc81ce137"
      define_method(:install) do
        bin.install "slatewave"
      end
    end
  end

  test do
    assert_match "slatewave version", shell_output("#{bin}/slatewave --version")
  end
end
