# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slatewave < Formula
  desc "One palette across every tool you live in — install the Slatewave family from one CLI."
  homepage "https://getslatewave.com"
  version "0.0.14"
  license "WTFPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.14/slatewave-cli_0.0.14_darwin_amd64.tar.gz"
      sha256 "e4e1e534857d950ddccaa29360b5730408b19e55859d0fc0cfbe2ea10b25db85"

      define_method(:install) do
        bin.install "slatewave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.14/slatewave-cli_0.0.14_darwin_arm64.tar.gz"
      sha256 "3e7e229544d7d8b97b8fc43efe7369b325d47714bb87f2499c941c3d097cc10f"

      define_method(:install) do
        bin.install "slatewave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.14/slatewave-cli_0.0.14_linux_amd64.tar.gz"
      sha256 "26ffd8fde7a98cb3d8664fa627aa0e141996a3694c128b4874687bb2934481b0"
      define_method(:install) do
        bin.install "slatewave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinlangleyjr/slatewave-cli/releases/download/v0.0.14/slatewave-cli_0.0.14_linux_arm64.tar.gz"
      sha256 "2bbe5459f76b585cbcb06137b27e2a88cccb9f09acdbe59f8e8dcda32a8de1cf"
      define_method(:install) do
        bin.install "slatewave"
      end
    end
  end

  test do
    assert_match "slatewave version", shell_output("#{bin}/slatewave --version")
  end
end
